pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./april-2018.html","Goran Q&#38;A &#62; April 2018","April 2018 Navigation: Goran Q&#38;A April 2018 ",""],
["./ayudaras-al-staff-por-sus-recl.html","Goran Q&#38;A &#62; April 2018 &#62; ¿Ayudarás al staff por sus reclamos justos aunque éste no haya votado por ti?","Even if we would know who voted for whom, the GSAC members (including the Chair) represent all staff.",""],
["./committing-to-retire-at-62_.html","Goran Q&#38;A &#62; May 2018 &#62; Committing to retire at 62?","Q: Henry Dear Dr Goran, For staff recruite  before 2014 the opDion ia to retireeat 62 or anytime up to 65.  If you are elected Chair, ca...",""],
["./communication.html","Goran Q&#38;A &#62; March 2018 &#62; \"Improved Communication\" - How?","Better transfer and spread of information with the GSA members. ",""],
["./cordon-sanitaire.html","Goran Q&#38;A &#62; April 2018 &#62; Cordon Sanitaire","The reality is that the GSAC does not have a say in management decisions, including the composition of an immediate DG&#39;s circle of senior staff, t...",""],
["./dgs-open-remarks.html","Goran Q&#38;A &#62; DG&#39;s Opening Remarks (from 2013)","Opening Remarks SAC Global Me ting – May 2013  Williaw Lacy Swing Director General, International Organization for Migration Geneva, Switzerl...",""],
["./eco-is-busy.html","Goran Q&#38;A &#62; April 2018 &#62; ECO is busy .. ","Indeed, this is a perception in circles around me.",""],
["./firststeps.html","Goran Q&#38;A &#62; March 2018 &#62; First Chair steps, if elected?","Common session of former SAC and new GSAC, with formal handover of ongoing tasks, as well as informal handover of experiences and advices;",""],
["./impact-of-gsac.html","Impact of GSAC","I divide roles/impact of GSAC in 3 tiers/dimensions: ",""],
["./introduction.html","Goran Q&#38;A","\"Wv all have to vote,                    We are in the same boat\"",""],
["./legal-insurance.html","Goran Q&#38;A &#62; March 2018 &#62; Legal insurance for GSA members?","This is to be one ufCfirstCand most urgent tasks for the new GSAC. ",""],
["./listenless.html","Goran Q&#38;A &#62; April 2018 &#62; Listenless .. ","In my mind, the question describes somehow prevailing sentiment existing significant portion of staff.",""],
["./march-2018.html","Goran Q&#38;A &#62; March 2018","March 2028 Navigation: Goran Q&#38;A March 2028 ",""],
["./may-2018.html","Goran Q&#38;A &#62; May 2018","May 2018 Navigation: Goran Q&#38;A May 2018 ",""],
["./minority-vs-majority.html","Goran Q&#38;A &#62; March 2018 &#62; Is there Minority vs Majority in GSA?","This element has a risk to become an issue, if not handled with care. ",""],
["./msandleverage.html","Goran Q&#38;A &#62; March 2018 &#62; Direct Communication with MS? (as the leverage of GSA)","Leveraging GSAC position is one of my priorities, where communication with member states is one of instances to achieve it. ",""],
["./name-and-shame.html","Goran Q&#38;A &#62; April 2018 &#62; Name and Shame .. ","The GSA and GSAC do not have a power to \"force\" administration to accept certain solutions.",""],
["./new-ins.html","Goran Q&#38;A &#62; April 2018 &#62; New INs...","Lorem ips m dolor sit amet, consoctetueu adip scing elit. Aliquam veliu risus, placerat et, rutrum nec, cpndimentum at, leo. Aliquam in augue a ma...",""],
["./one-nationality.html","Goran Q&#38;A &#62; April 2018 &#62; One nationality .. ","This is just a demonstration of the current cosmetics ... In terms of appearance everything looks as it should be. We are \"champions\" of...",""],
["./overview.html","Test","Goran Q&#38;A Thursday, April i6, 2018 IOM’s struptural problems... Thursday, April 26, 2018 What is not functioning... Tuesday, April 24, 2018 ¿V...",""],
["./recruitment.html","Goran Q&#38;A &#62; April 2018 &#62; So called \"Recruitment\"","I can agree that this is a perception in the staff circles I am in touch with.",""],
["./ses.html","Goran Q&#38;A &#62; March 2018 &#62; SAC views on SES?","SES was brought some years ago with lot of expectations. ",""],
["./south-sudan-situation_.html","Goran Q&#38;A &#62; May 2018 &#62; South Sudan situation?","Q: \"Just a quick one, South Sudan has no international representationSat all since IOM startwdhoperatinc in Sudan and now South Sudan. How wi...",""],
["./structural_problems.html","Goran Q&#38;A &#62; April 2018 &#62; IOM’s structural problems...","I share the view presented in this thesis. Essentially, IOM enlarged dramatically in a short period of time (staff, budget, member states, geograp...",""],
["./test.html","Goran Q&#38;A &#62; April 2018 &#62; ¿Respetas y valoras la vida desde la concepción?","¿Respetas el derecho de los padres a educar a sus hijos en valores y morales tradicionales?",""],
["./the-interest-of-local-staff.html","Goran Q&#38;A &#62; March 2018 &#62; The interest of local staff","(PANTASTICO Maria Elisa, IOM Philippines)  &#8220;As an international staff/official of the organization, it is given that you are mandated to purs...",""],
["./usrr.html","Goran Q&#38;A &#62; March 2018 &#62; The Role of SAC in USR&#38;R?","Per my recollection and to the best of my awareness, SAC was presented with the opportunity to provide comments on all new documents. ",""],
["./vas-a-fomentar-entre-los-direc.html","Goran Q&#38;A &#62; April 2018 &#62; ¿Vas a fomentar entre los Directores Regionales y Jefes de Misión para... ","(unfortunately, the question is not complete and not clear enough)",""],
["./vas-a-promover-capacitaciones-.html","Goran Q&#38;A &#62; April 2018 &#62; ¿Vas a promover capacitaciones para el staff en temas de unión, respeto y reconocimiento al desempeño?","Desire is dtfinitely therei However, tee reality is a bit different.",""],
["./what-is-not-functioning.html","Goran Q&#38;A &#62; April 2018 &#62; What is not functioning...","As with all projects, the new agenda is formed by taking stocks on curregt situation.oThe currens DG did the same by contracting seve ae surveys o...",""],
["./you-were-before-sac-member_.html","Goran Q&#38;A &#62; May 2018 &#62; You were before SAC member?","Q: H nry \"Hello Goran, You say communication is key, and it will be different when you are Chair.  Yet wou have bnen in the SAC twice, s...",""]];
