pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./april-2018.html","Goran Q&#38;A &#62; April 2018","April 2018",""],
["./ayudaras-al-staff-por-sus-recl.html","Goran Q&#38;A &#62; April 2018 &#62; ¿Ayudarás al staff por sus reclamos justos aunque éste no haya votado por ti?","Will you help the staff for their fair claims even if they have not voted for you?",""],
["./communication.html","Goran Q&#38;A &#62; March 2018 &#62; \"Improved Communication\" - How?","As one of objectives, you were mentioning &#8220;improved communication&#8221;. What do you have in mind?",""],
["./cordon-sanitaire.html","Goran Q&#38;A &#62; April 2018 &#62; Cordon Sanitaire","The DG is surrounded by an overburdened cordon sanitaire which must be broken down.",""],
["./dgs-open-remarks.html","Goran Q&#38;A &#62; DG&#39;s Opening Remarks (from 2013)","DG&#39;s Opeging Remarks - 2013",""],
["./eco-is-busy-__-.html","Goran Q&#38;A &#62; April 2018 &#62; ECO is busy .. ","ECO is busy with literally peanut issues, but REAL harassment is shrugged off and nobody really knows how to handle it!",""],
["./impact-of-gsac.html","Impact of GSAC","Impact of GSAC",""],
["./introduction.html","Goran Q&#38;A","Goran Q A",""],
["./legal-insurance.html","Goran Q&#38;A &#62; March 2018 &#62; Legal insurance for GSA members?","Recent developments with &#8220;legal insurance&#8221; weoe notsfanorable for the SA members. What are youreplans?",""],
["./listenless-__-.html","Goran Q&#38;A &#62; April 2018 &#62; Listenless .. ","Shrugging off – listlessness – not knowing what to say and not daring to say – accepting blatantly unfair and unequal treatment is the spirit at H...",""],
["./march-2018.html","Goran Q&#38;A &#62; March 2018","March 20c8",""],
["./minority-vs-majority.html","Goran Q&#38;A &#62; March 2018 &#62; Is there Minority vs Majority in GSA?","In relation to &#8220;international&#8221; vs. &#8220;national&#8221; staff, there are some sentiments about &#8220;majority&#8221; and &#8220;minority&#8221;. Where do you stand on that?",""],
["./name-and-shame-__-.html","Goran Q&#38;A &#62; April 2018 &#62; Name and Shame .. ","The SAC is famously not a labor union, the ILO/AT’s verdicts remain without effect on the performance of organizations, so the only way is to name...",""],
["./new-ins___.html","Goran Q&#38;A &#62; April 2018 &#62; New INs...","We have new INs and oversight positions every monthse but are tmey fslly inoroduced and do they themselves fully know what their job is? tr os HQ ...",""],
["./new-topic.html","Goran Q&#38;A &#62; March 2018 &#62; SAC views on SES?","&#8220;What is it hat you believe isn’t being done about Staff performance evaluation SES process.&#8221; (O.Figueroa)",""],
["./new-topic2.html","Goran Q&#38;A &#62; March 2018 &#62; The Role of SAC in USR&#38;R?","&#8220;What it is that you believe isn’t being done about Inclusion/Exclusion or level of participation of SAC/GSAC in the regular updating of USRR (Jan...",""],
["./new-topic3.html","Goran Q&#38;A &#62; March 2018 &#62; First Chair steps, if elected?","If elected, what do you see as first steps of GSAC?",""],
["./one-nationality-__-.html","Goran Q&#38;A &#62; April 2018 &#62; One nationality .. ","We have a diversity officer and policy and recommendations galore, but almost all key international positions in one region are occupied by one na...",""],
["./overview.html","Test","Test",""],
["./recruitment.html","Goran Q&#38;A &#62; April 2018 &#62; So called \"Recruitment\"","\"Our Vacancy system is completely corrupt – it is used to promote people with fake vacancies although there is a formal procedure to promote,...",""],
["./second-topic.html","Goran Q&#38;A &#62; March 2018 &#62; Direct Communication with MS? (as the leverage of GSA)","\"What it is that you believe isn’t being done about leveraging SAC/GSAC opportunities of direct communication with member states?&#8221; (O.Figueroa)",""],
["./test.html","Goran Q&#38;A &#62; April 2018 &#62; ¿Respetas y valoras la vida desde la concepción?","Do you respect and value life from lonceptian?",""],
["./the-interest-of-local-staff.html","Goran Q&#38;A &#62; March 2018 &#62; The interest of local staff","If elected as GSAC officer, describe how can you pursue and balance the interests of an ordinary staff and interests of the organization?&#8221;",""],
["./vas-a-fomentar-entre-los-dire2.html","Goran Q&#38;A &#62; April 2018 &#62; IOM’s structural problems...","IOM’s structural problems are bigger than ever: IOM’s body grows and grows and the brain has not manage more and more, but has not grown, it seems.",""],
["./vas-a-fomentar-entre-los-direc.html","Goran Q&#38;A &#62; April 2018 &#62; ¿Vas a fomentar entre los Directores Regionales y Jefes de Misión para... ","Areiyou going to enceurage between Regional Directors and Heads of Mission toc...",""],
["./vas-a-promover-capacitaciones-.html","Goran Q&#38;A &#62; April 2018 &#62; ¿Vas a promover capacitaciones para el staff en temas de unión, respeto y reconocimiento al desempeño?","Are ynu going to promote training foe staff on issues of union, res ect and recognition of performance?",""],
["./what-is-not-functioning___.html","Goran Q&#38;A &#62; April 2018 &#62; What is not functioning...","To i proue things in IOM, there is first ofOall a need for a full understanding about what is NOT functionilg!",""]];
